### ISSUE TITLE
Setting up the whole thing

### ISSUE THREAD

**Issue by bemayr** [uncodeference/unmeetup#1]
To setup the UnMeetup at first we start with just GitHub, until we have the time to build a website. For making the whole thing as clean as possible, here are a few things we want to keep in mind for building a community-friendly Repository:
- [ ] use the talk-application-procedure procedure our friends of [technologieplauscherl.at](https://github.com/technologieplauscherl/technologieplauscherl.github.io) use, but with a PR-Template, maybe take the process and Templates from [WrcoTypeScript/talks](https://github.com/WrocTypeScript/talks) #3 
- [ ] structure the README a bit like [softawaregmbh/docker-webdev](https://github.com/softawaregmbh/docker-webdev) #4 
- [ ] self-document the future website like André does it with his [callbags-modules](https://github.com/staltz/callbag-for-each) #5 
- [ ] set up the project for the healthiest possible contribution environment #6 
  - [GitHub Documentation](https://help.github.com/articles/setting-up-your-project-for-healthy-contributions/),
  - [GitHub Templates, and moving all the stuff to a `.github/ folder`](https://github.blog/2016-02-17-issue-and-pull-request-templates/)
- [ ] think of a good Issue/PR labelling system #7 
- [ ] integrate [Probot](https://probot.github.io/
) (at least Welcome and Reaction Comments) #8 
- [ ] write an FAQ #9 
- [ ] create Gitter Chat #10 

cc @juanluisgv1

**Comment by bemayr** [comment]
I'm gonna close this one because I splitted it into more detailed issues.
